services:
  esp32-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: root
        USER_UID: 1000
        USER_GID: 1000
    privileged: true
    user: root
    tty: true
    stdin_open: true
    environment:
      IDF_PATH: /opt/esp/idf
      XTENSA_GDB: /opt/esp/tools/xtensa-esp-elf-gdb/16.2_20250324/xtensa-esp-elf-gdb/bin/xtensa-esp32s3-elf-gdb
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    volumes:
      - ..:/home/user/Documents/solaris-software:cached
    network_mode: host
    working_dir: /home/user/Documents/solaris-software
